# -*- coding: utf-8 -*-
"""
Problem 12: Highly divisible triangular number

The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""

from time import time
start = time()



# maak een lijstje met driehoeksgetallen
driehoek = []
for x in range(1, 101):
	driehoek.append(int((float(x)/2 + 0.5) * x))

# testen door hoeveel getallen je ieder driehoeksgetal kan delen
z = 0
for i in driehoek:
	x = 1
	#print i,
	for j in range(0, i/2):
		if i % (i/2 - j) == 0:
		#	print i/2 - j,
			x += 1
	if x > z:
		z = x
		print i, z

print '\nTijd: ', time() - start
